export type TemplateColor = { name: string; label: string };
export type TemplateEnvelop = { label: string; img: string };

export type Template = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  features: string[];
  img: string;
  envelops: TemplateEnvelop[];
  colors: TemplateColor[];
  music: string[];
  faq: { q: string; a: string }[];
  price: string;
};

const BASE = "https://sponsalia.app/_next/image?url=%2Fassets%2Fmarketing%2Ftemplates%2F";

export const templates: Template[] = [
  {
    slug: "bloom",
    name: "Bloom",
    tagline: "LINTEN EN AQUARELROZEN",
    description: "Bloom is het ontwerp voor wie een digitale trouwkaart wil die met de hand geschilderd lijkt. De voorkant is een ovale aquarelcartouche: een satijnen strik bovenaan, twee rozenranken die langs de zijkanten omlaag vallen en onderaan weer samenkomen, en in het ovaal jullie namen in fijn Engels schrift. Daarna verandert het papier met het verhaal — de secties van de dag blijven licht, terwijl aftelklok, dresscode en afsluiting een gestreept aquarelpapier worden met daarop een kaart met golvende rand.",
    features: [
      "Geschilderde voorkant: ovale cartouche, satijnen strik en rozenranken",
      "De kleur kiezen jullie: linten en rozen volgen het palet, de blaadjes blijven groen",
      "Gestreepte aquarelbanen met een kaart met golvende rand",
      "Geïllustreerd dagprogramma: een tekening bij elk moment",
      "Jullie eigen foto in plaats van de voorkant, of achter de banen",
      "17 talen: elke gast leest de uitnodiging in de eigen taal",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=1200&q=75",
    envelops: [
      { label: "Origineel", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Hemelsblauw", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Lavendel", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Saliegroen", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "hemelsblauw", label: "Hemelsblauw" },
      { name: "lavendel", label: "Lavendel" },
      { name: "saliegroen", label: "Saliegroen" },
      { name: "bordeaux", label: "Bordeaux & Goud" },
    ],
    music: ["Amber Glow", "Warm Embrace", "Romantic Piano", "Most Beautiful Day", "Promise of Love", "Wedding Joy", "Geen"],
    faq: [
      { q: "Kan ik het roze veranderen?", a: "Ja: linten, strikken, rozen en strepen zijn in één tint geschilderd die het palet volgt — poederroze standaard, of hemelsblauw, lavendel, saliegroen of een vrije kleur. Het blad blijft groen, zodat de aquarel nooit een plat silhouet wordt." },
      { q: "Kan ik een eigen foto gebruiken?", a: "Ja, op twee plekken: in plaats van de geschilderde voorkant en achter de aftelklok, de dresscode en de afsluiting. Op de voorkant vult de foto het hele scherm, cartouche inbegrepen." },
      { q: "Kunnen gasten direct vanuit de uitnodiging bevestigen?", a: "Ja: de RSVP zit erin. Elke gast antwoordt met één tik en geeft allergieën en menuvoorkeuren door, en jullie zien alle antwoorden in het dashboard." },
    ],
    price: "89",
  },
  {
    slug: "volta-celeste",
    name: "Volta Celeste",
    tagline: "GESCHILDERDE LUCHT EN STUCWERK",
    description: "Volta Celeste is het sjabloon voor stellen die willen dat hun digitale trouwkaart omhoog kijkt, zoals onder het beschilderde plafond van een Italiaanse villa. Hij opent als een echte kaart: in drieën gevouwen, met rococo-rankwerk blind in het papier gepreegd, dichtgebonden met een witte stoffen strik die bij aanraking losgaat en de kleppen laat openvallen. Daarachter ligt een geschilderde lucht — gouden en blauwe wolken, een lijst van wit rankwerk die langs beide zijden omhoog klimt, twee duiven in vlucht — en in de vrije kolom in het midden staan de namen van het paar, de datum en de plaats.",
    features: [
      "Video-opening: de stoffen strik gaat los en de kaart valt open",
      "Twee papieren voor de envelop: ivoor of hemelsblauw, dezelfde lucht erachter",
      "Geschilderde hero: de lucht met zijn duiven en de namen in de lijst",
      "Secties op gescheurd papier, op de lucht gelegd",
      "Alles licht: geen donkere sectie, warme bruin-olijve inkt",
      "17 talen: elke gast leest de uitnodiging in de zijne",
      "Aanpasbare kleuren en lettertypes",
    ],
    img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=1200&q=75",
    envelops: [
      { label: "Ivoor", img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=400&q=75" },
      { label: "Hemelsblauw", img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "champagne", label: "Champagne & Goud" },
      { name: "sage", label: "Licht Salie" },
    ],
    music: ["Amber Glow", "Sky Waltz", "Dolce Vita", "Wedding Joy", "Geen"],
    faq: [
      { q: "Hoe werkt het openen met de strik?", a: "De gast tikt op het scherm: de stoffen strik gaat los, de in drieën gevouwen kaart opent en de geschilderde lucht verschijnt. Het laatste beeld van de video is precies het beeld van de uitnodiging, dus de overgang gaat zonder snede." },
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De lucht, het rankwerk en de inkt volgen jullie palet. Je kiest uit de beschikbare kleurvarianten of geeft een eigen kleur op." },
      { q: "Kunnen gasten direct bevestigen?", a: "Ja, de RSVP zit ingebouwd. Elke gast bevestigt met één tik en vult allergieën en menuvoorkeuren in." },
    ],
    price: "89",
  },
  {
    slug: "zomertuin",
    name: "Zomertuin",
    tagline: "GROENE TUIN EN ROZE KANT",
    description: "Zomertuin neemt jullie gasten mee naar een Italiaanse tuin in volle bloei — weelderig groen, roze bloemen en een delicate cartouche van roze kant omlijst de namen van het bruidspaar.",
    features: [
      "Botanische illustraties in aquarel",
      "Zachte groene en roze tinten",
      "Kant-cartouche rond de namen",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypes",
    ],
    img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=1200&q=75",
    envelops: [
      { label: "Origineel", img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=400&q=75" },
      { label: "Roze", img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "peach", label: "Perzik & Goud" },
      { name: "lavender", label: "Lavendel" },
    ],
    music: ["Garden Waltz", "Amber Glow", "Tender Rose", "Geen"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja, alle bloem- en kanttinten volgen jullie palet." },
      { q: "Kunnen gasten bevestigen?", a: "Ja, de RSVP zit ingebouwd." },
    ],
    price: "89",
  },
  {
    slug: "villa-aurora",
    name: "Villa Aurora",
    tagline: "TERRAS BIJ ZONSONDERGANG",
    description: "Villa Aurora plaatst jullie gasten op een terras bij zonsondergang — warme oranje en gouden tinten, een mediterraan silhouet en een gevoel van stille luxe.",
    features: ["Warme zonsondergang-palet", "Mediterraan architectuurdetail", "17 talen beschikbaar", "Aanpasbare kleuren"],
    img: BASE + "villa-aurora-en-vetrina-50b36ee0.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "villa-aurora-en-vetrina-50b36ee0.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "gold", label: "Goud & Cream" }],
    music: ["Dolce Vita", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "het-zwanenmeer",
    name: "Het Zwanenmeer",
    tagline: "ROMANTISCH EN LUCHTIG",
    description: "Het Zwanenmeer zweeft tussen droom en werkelijkheid — twee zwanen op een spiegelend meer, zachte blauwe tinten en een algehele luchtigheid.",
    features: ["Zwanen-illustratie als hero", "Zachte blauw-grijze tinten", "17 talen beschikbaar"],
    img: BASE + "lago-dei-cigni-en-vetrina-6e0256ed.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "lago-dei-cigni-en-vetrina-6e0256ed.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "blush", label: "Blush & Zilver" }],
    music: ["Tender Rose", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "villa-cortina",
    name: "Villa Cortina",
    tagline: "HET GORDIJN OPENT DE ZAAL",
    description: "Villa Cortina opent als een theatergordijn — fluwelen plooien wijken uiteen en onthullen een zaal van kant en kristal.",
    features: ["Theatraal gordijn-opening", "Kristal en kant details", "17 talen beschikbaar"],
    img: BASE + "villa-cortina-en-vetrina-553a7717.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "villa-cortina-en-vetrina-553a7717.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "bordeaux", label: "Bordeaux & Goud" }],
    music: ["Grand Entrance", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "minimale-couture",
    name: "Minimale Couture",
    tagline: "ESSENTIEEL, RUIMTE EN ADEM",
    description: "Minimale Couture zegt meer door minder — strakke lijnen, veel wit en luxe typografie.",
    features: ["Clean minimalistisch design", "Luxe typografie", "17 talen beschikbaar"],
    img: BASE + "couture-minimale-en-vetrina-93e7c6cd.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "couture-minimale-en-vetrina-93e7c6cd.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "black", label: "Zwart & Wit" }],
    music: ["Tender Rose", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "betoverd-bos",
    name: "Betoverd Bos",
    tagline: "GESCHILDERD BOS EN WILDE ROZEN",
    description: "Betoverd Bos voert jullie gasten diep in een geschilderd woud — wilde rozen klimmen langs eikenhouten paden.",
    features: ["Geschilderd boslandschap", "Wilde rozen en botanisch groen", "17 talen beschikbaar"],
    img: BASE + "incanto-nel-bosco-en-vetrina-6c056d35.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "incanto-nel-bosco-en-vetrina-6c056d35.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "forest", label: "Diep Groen" }],
    music: ["Garden Waltz", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "riviera-70",
    name: "Riviera 70",
    tagline: "ZONNIG EN VINTAGE",
    description: "Riviera 70 katapulteert jullie gasten naar een zonnige kust in de jaren zeventig — warm oranje, oud geel en retro typografie.",
    features: ["Retro jaren 70 design", "Warme kust-palet", "17 talen beschikbaar"],
    img: BASE + "riviera-70-en-vetrina-253c0193.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "riviera-70-en-vetrina-253c0193.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "coral", label: "Koraal & Goud" }],
    music: ["Summer Groove", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "italiaanse-aquarel",
    name: "Italiaanse Aquarel",
    tagline: "MAJOLICA EN KUST IN AQUAREL",
    description: "Italiaanse Aquarel combineert de kleurrijke majolica-tegels van Amalfi met luchtige aquarelwassen van de kust.",
    features: ["Majolica-geïnspireerde details", "Aquarel kust-illustraties", "17 talen beschikbaar"],
    img: BASE + "acquerello-italia-en-vetrina-3869b8cc.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "acquerello-italia-en-vetrina-3869b8cc.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "lemon", label: "Citroen & Blauw" }],
    music: ["Dolce Vita", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "oro-antico",
    name: "Oro Antico",
    tagline: "BEIGE EN OUD GOUD",
    description: "Oro Antico ademt de grandeur van een oud Italiaans palazzo — beige muren, verguld stucwerk en bloemmotieven in goud.",
    features: ["Antiek goud accenten", "Bloemrijke ornamenten", "17 talen beschikbaar"],
    img: BASE + "oro-antico-en-vetrina-22d36ceb.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "oro-antico-en-vetrina-22d36ceb.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "platinum", label: "Platina & Ivoor" }],
    music: ["Amber Glow", "Golden Hour", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "tuscany-chic",
    name: "Tuscany Chic",
    tagline: "WARM EN VERFIJND, EN PLEIN AIR",
    description: "Tuscany Chic combineert de warmte van Toscaans licht met moderne verfijning — okerkleurige velden, cypressen en open-lucht-gevoel.",
    features: ["Toscaans landschapsdetail", "Warme oker en terracotta tinten", "17 talen beschikbaar"],
    img: BASE + "tuscany-chic-en-vetrina-3646f639.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "tuscany-chic-en-vetrina-3646f639.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "olive", label: "Olijf & Goud" }],
    music: ["Dolce Vita", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "gouden-uur",
    name: "Gouden Uur",
    tagline: "WARM AVONDLICHT",
    description: "Gouden Uur vangt het magische moment net vóór zonsondergang — warm goud, diepe schaduwen en een intiem gevoel.",
    features: ["Gouden zonsondergang-sfeer", "Intiem en romantisch", "17 talen beschikbaar"],
    img: BASE + "tipografico-moderno-en-vetrina-2c921489.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "tipografico-moderno-en-vetrina-2c921489.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "copper", label: "Koper & Goud" }],
    music: ["Golden Hour", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "de-geheime-tuin",
    name: "De Geheime Tuin",
    tagline: "ROZENBOOG EN ITALIAANSE TUIN",
    description: "De Geheime Tuin leidt jullie gasten door een verborgen poort — een rozenboog omlijst de ingang, weelderig groen verbergt oude stenen muren.",
    features: ["Rozenboog als visuele poort", "Italiaanse tuin-illustraties", "17 talen beschikbaar"],
    img: BASE + "giardino-segreto-en-vetrina-c0e0298d.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "giardino-segreto-en-vetrina-c0e0298d.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "rose", label: "Roos & Groen" }],
    music: ["Garden Waltz", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "tratto-d-inchiostro",
    name: "Tratto d'Inchiostro",
    tagline: "PENLIJNEN OP PAPIER",
    description: "Tratto d'Inchiostro is een ode aan de handgeschreven brief — lijnillustraties in één enkele inkt op crèmepapier.",
    features: ["Handgetekende lijnillustraties", "Monochroom inkt-palet", "17 talen beschikbaar"],
    img: BASE + "tratto-inchiostro-en-vetrina-48f6d0e0.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "tratto-inchiostro-en-vetrina-48f6d0e0.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "sepia", label: "Sepia" }],
    music: ["Tender Rose", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "idillio",
    name: "Idillio",
    tagline: "GOUDEN STRIK EN ZWANEN",
    description: "Idillio is licht, lucht en liefde — een gouden strik, witte zwanen en een algehele helderheid die past bij een zomerse bruiloft.",
    features: ["Gouden strik als centraal element", "Witte zwanen-illustratie", "17 talen beschikbaar"],
    img: BASE + "idillio-en-vetrina-4806113a.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "idillio-en-vetrina-4806113a.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "gold", label: "Goud & Wit" }],
    music: ["Golden Hour", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "romantisch-botanisch",
    name: "Romantisch Botanisch",
    tagline: "BLADEREN EN BLOEMEN, DELICAAT",
    description: "Romantisch Botanisch omhult elke sectie met delicate botanische illustraties — varens, bloesem en wilde bloemen.",
    features: ["Botanische illustraties", "Delicate groene en roze tinten", "17 talen beschikbaar"],
    img: BASE + "botanico-romantico-en-vetrina-5a476f93.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "botanico-romantico-en-vetrina-5a476f93.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "forest", label: "Diep Groen" }],
    music: ["Garden Waltz", "Amber Glow", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "strawberry-matcha",
    name: "Strawberry Matcha",
    tagline: "FRIS EN SPEELS",
    description: "Strawberry Matcha is fris, speels en onverwacht — matcha-groen en aardbeirood creëren een uitnodiging die direct opvalt.",
    features: ["Speels matcha & aardbei palet", "Modern en fris design", "17 talen beschikbaar"],
    img: BASE + "strawberry-matcha-en-vetrina-4c490953.jpg&w=1200&q=75",
    envelops: [{ label: "Origineel", img: BASE + "strawberry-matcha-en-vetrina-4c490953.jpg&w=400&q=75" }],
    colors: [{ name: "origineel", label: "Origineel" }, { name: "matcha", label: "Matcha & Cream" }],
    music: ["Fresh Morning", "Garden Waltz", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
  {
    slug: "toile-de-jouy",
    name: "Toile de Jouy",
    tagline: "TOILE IN VIER TINTEN",
    description: "Toile de Jouy is een klassieke toile-print in vier tinten op crème papier met landelijke taferelen en een zilveren of wit lint.",
    features: ["Klassieke toile-print illustraties", "Vier kleurvarianten", "Zilver of wit lint", "17 talen beschikbaar"],
    img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=1200&q=75",
    envelops: [
      { label: "Toile Blauw", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Rood", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Groen", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Zwart", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "blauw", label: "Toile Blauw" },
      { name: "rood", label: "Toile Rood" },
      { name: "groen", label: "Toile Groen" },
      { name: "zwart", label: "Toile Zwart" },
    ],
    music: ["Versailles", "Tender Rose", "Geen"],
    faq: [{ q: "Kunnen gasten bevestigen?", a: "Ja." }],
    price: "89",
  },
];

export function getTemplate(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}
