export type TemplateColor = { name: string; label: string };
export type TemplateEnvelop = { label: string; img: string };

export type Template = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  features: string[];
  img: string;
  envelops: TemplateEnvelop[];
  colors: TemplateColor[];
  music: string[];
  faq: { q: string; a: string }[];
  price: string;
  openingStyle: "bow" | "trifold" | "curtain" | "wave" | "floral" | "fold";
};

const BASE = "https://sponsalia.app/_next/image?url=%2Fassets%2Fmarketing%2Ftemplates%2F";

export const templates: Template[] = [
  {
    slug: "bloom",
    name: "Bloom",
    tagline: "LINTEN, STRIKKEN EN AQUARELROZEN",
    description: "Bloom is voor het stel dat wil dat de uitnodiging aanvoelt als iets wat je hebt gevonden in een antiekwinkel — met de hand geschilderd, met liefde gemaakt. De voorkant is een ovale cartouche omgeven door rozenranken in aquarel, gebonden met een satijnen strik. Jullie namen staan in fijn Engels schrift in het midden. De rest van de uitnodiging ademt dezelfde sfeer: lichte secties met bloemmotieven in de hoeken, en een gestreept aquarelpapier voor de aftelklok, dresscode en afsluiting. De kleur van de rozen, linten en strepen volgt jullie palet — poederroze, hemelsblauw, lavendel of wat jullie maar kiezen. De blaadjes blijven altijd groen, want zo werkt een aquarel.",
    features: [
      "Geschilderde voorkant: ovale cartouche, satijnen strik en rozenranken",
      "De kleur van linten en rozen volgt jullie palet, de blaadjes blijven groen",
      "Gestreept aquarelpapier voor aftelklok, dresscode en afsluiting",
      "Geïllustreerd dagprogramma: een tekening bij elk moment van de dag",
      "Jullie eigen foto als voorkant, of achter de gestreepte secties",
      "17 talen: elke gast leest de uitnodiging in zijn of haar eigen taal",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=1200&q=75",
    envelops: [
      { label: "Ivoor", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Poederroze", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Hemelsblauw", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
      { label: "Lavendel", img: BASE + "bloom-en-vetrina-96e6b193.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "hemelsblauw", label: "Hemelsblauw" },
      { name: "lavendel", label: "Lavendel" },
      { name: "saliegroen", label: "Saliegroen" },
      { name: "bordeaux", label: "Bordeaux & Goud" },
    ],
    music: ["Amber Glow", "Warm Embrace", "Romantic Piano", "Most Beautiful Day", "Promise of Love", "Wedding Joy", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleur van de rozen aanpassen?", a: "Ja. De rozen, linten, strikken en strepen zijn in één tint geschilderd die jullie palet volgt. De blaadjes blijven groen zodat de aquarel zijn diepte behoudt. Je kunt kiezen uit de beschikbare paletten of een eigen kleur opgeven." },
      { q: "Kan ik een eigen foto gebruiken?", a: "Ja, op twee plekken: als vervanging van de geschilderde voorkant, of achter de aftelklok, dresscode en afsluiting. Op de voorkant vult de foto het volledige scherm, inclusief de cartouche eroverheen." },
      { q: "Hoe werkt de RSVP?", a: "De bevestigingspagina zit ingebouwd. Elke gast bevestigt met één tik, geeft dieetwensen door en kiest een menu. Jullie zien alle antwoorden in real time in het dashboard." },
      { q: "In hoeveel talen is de uitnodiging beschikbaar?", a: "In 17 talen. Elke gast kiest zelf de taal, of de uitnodiging past zich automatisch aan op basis van de taalinstellingen van het apparaat." },
    ],
    price: "89",
    openingStyle: "bow",
  },
  {
    slug: "volta-celeste",
    name: "Volta Celeste",
    tagline: "GESCHILDERDE LUCHT EN WIT STUCWERK",
    description: "Volta Celeste kijkt omhoog — zoals je doet als je voor het eerst een beschilderd plafond ziet in een Italiaanse villa. De uitnodiging arriveert als een echte papieren kaart: in drieën gevouwen, met rococo-rankwerk blind in het papier gepreegd en dichtvouwen met een witte stoffen strik. Bij aanraking gaat de strik los, vallen de kleppen open en verschijnt de geschilderde lucht. Gouden en blauwe wolken, twee duiven in vlucht, een lijst van wit rankwerk langs de zijkanten — en in de vrije kolom in het midden jullie namen, de datum en de locatie. De secties daarna liggen als vellen gescheurd papier op de lucht, en de inkt is warm bruin-olijf, niet zwart. Er is geen donkere sectie, geen scherp contrast: alleen licht, lucht en de namen van het stel.",
    features: [
      "Strik-opening: de stoffen strik gaat los en de kaart valt in drieën open",
      "Twee enveloptypes: ivoor papier of hemelsblauw, dezelfde lucht erachter",
      "Geschilderde lucht als hero met duiven en namen in het rankwerk",
      "Secties als gescheurd papier op de lucht gelegd",
      "Alles licht: geen donkere sectie, warme bruin-olijve inkt",
      "17 talen: elke gast leest de uitnodiging in zijn eigen taal",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=1200&q=75",
    envelops: [
      { label: "Ivoor", img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=400&q=75" },
      { label: "Hemelsblauw", img: BASE + "volta-celeste-en-vetrina-63b82e9f.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "champagne", label: "Champagne & Goud" },
      { name: "sage", label: "Licht Salie" },
    ],
    music: ["Amber Glow", "Dolce Vita", "Sky Waltz", "Wedding Joy", "Geen muziek"],
    faq: [
      { q: "Hoe werkt de strik-opening?", a: "De gast tikt op het scherm. De stoffen strik trilt los, de kaart valt open in drieën en de geschilderde lucht verschijnt. Het laatste beeld van de animatie gaat naadloos over in de uitnodiging zelf." },
      { q: "Wat is het verschil tussen het ivoren en hemelsblauwe papier?", a: "Alleen de envelop en de achtergrond van de secties veranderen van tint. De geschilderde lucht, het rankwerk en de duiven blijven hetzelfde." },
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De lucht, het rankwerk en de inkt volgen jullie palet. Je kiest uit de beschikbare varianten of geeft zelf een kleur op." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app. Elke gast bevestigt met één tik, geeft dieetwensen door en kiest een menu. Alles verschijnt in jullie dashboard." },
    ],
    price: "89",
    openingStyle: "trifold",
  },
  {
    slug: "zomertuin",
    name: "Zomertuin",
    tagline: "ITALIAANSE TUIN IN VOLLE BLOEI",
    description: "Zomertuin opent als een tuinpoort op een warme junidag — een cartouche van roze kant omlijst jullie namen, weelderig groen klimt langs de randen omhoog en aquarelbloemen vullen elke hoek. De sfeer is van een Italiaanse tuin die je nooit hebt gezien maar meteen herkent: overwoekerd, zacht en vol licht. Elke sectie heeft zijn eigen botanische rand, en de kleuren volgen de tuin van de locatie — of de kleur die jullie mooi vinden.",
    features: [
      "Kant-cartouche als voorkant met namen in fijn schrift",
      "Botanische aquarelranden in elke sectie",
      "Zachte groene en roze tinten, volledig aanpasbaar",
      "Geïllustreerd dagprogramma",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=1200&q=75",
    envelops: [
      { label: "Ivoor", img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=400&q=75" },
      { label: "Roze", img: BASE + "giardino-destate-en-vetrina-e4c79ec8.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "peach", label: "Perzik & Goud" },
      { name: "lavender", label: "Lavendel" },
    ],
    music: ["Garden Waltz", "Tender Rose", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleur van de bloemen aanpassen?", a: "Ja. De kant, de bloemen en de randen volgen jullie palet volledig." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik en geeft dieetwensen door." },
    ],
    price: "89",
    openingStyle: "floral",
  },
  {
    slug: "villa-aurora",
    name: "Villa Aurora",
    tagline: "GOUDEN LICHT OP EEN MEDITERRAAN TERRAS",
    description: "Villa Aurora vangt het moment net vóór het diner begint — de zon staat laag, het terras is gedekt en alles baadt in warm goud. De uitnodiging opent als de deuren van een Italiaans villa: twee panelen die uiteen gaan en het tafereel onthullen. Warme oker, zacht terracotta en een mediterraan silhouet dat tijdloos is. Voor het stel dat kiest voor stille grandeur boven uitbundigheid.",
    features: [
      "Terras-opening: twee deuren gaan uiteen",
      "Warm goud en mediterraan silhouet",
      "Lichte en donkere variant beschikbaar",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "villa-aurora-en-vetrina-50b36ee0.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "villa-aurora-en-vetrina-50b36ee0.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "gold", label: "Goud & Cream" },
      { name: "terracotta", label: "Terracotta" },
    ],
    music: ["Dolce Vita", "Amber Glow", "Sunset Serenade", "Geen muziek"],
    faq: [
      { q: "Kan ik een eigen foto gebruiken?", a: "Ja, als achtergrond van de hero-sectie." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "curtain",
  },
  {
    slug: "het-zwanenmeer",
    name: "Het Zwanenmeer",
    tagline: "TWEE ZWANEN OP EEN SPIEGELEND MEER",
    description: "Het Zwanenmeer zweeft. Twee witte zwanen op een stilstaand meer, een lucht die nauwelijks te onderscheiden is van het water en een kleurenpalet dat de grens tussen droom en werkelijkheid opzoekt. Zachte blauwgrijze tinten, geen scherpe lijnen — alleen die alomtegenwoordige rust die past bij een bruiloft waarbij je even wilt stilstaan. De opening is een golf die van het midden naar de randen gaat, zoals de deining die de zwanen achterlaten.",
    features: [
      "Golf-opening vanuit het midden",
      "Zwanen-illustratie als centrale hero",
      "Zachte blauw-grijze tinten",
      "Alles licht: geen donkere secties",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "lago-dei-cigni-en-vetrina-6e0256ed.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "lago-dei-cigni-en-vetrina-6e0256ed.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "blush", label: "Blush & Zilver" },
      { name: "midnight", label: "Middernachtsblauw" },
    ],
    music: ["Swan Lake", "Tender Rose", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. Het palet volgt jullie keuze volledig." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "wave",
  },
  {
    slug: "villa-cortina",
    name: "Villa Cortina",
    tagline: "HET GORDIJN GAAT OPEN, DE ZAAL VERSCHIJNT",
    description: "Villa Cortina is theater. Fluwelen gordijnen schuiven uiteen — langzaam, met gewicht — en geven een zaal vrij van kant, kristal en marmer. Dit is de uitnodiging voor het stel dat groot wil denken en niet bang is om te imponeren. De opening duurt iets langer dan bij de andere sjablonen, want dit moment verdient de tijd.",
    features: [
      "Theatraal gordijn dat opengaat bij aanraking",
      "Kristal- en kantdetails in elke sectie",
      "Rijke kleuren: bordeaux, marine of ivoor",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "villa-cortina-en-vetrina-553a7717.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "villa-cortina-en-vetrina-553a7717.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "bordeaux", label: "Bordeaux & Goud" },
      { name: "navy", label: "Marine & Zilver" },
    ],
    music: ["Grand Entrance", "Velvet Night", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Hoe werkt de gordijn-opening?", a: "De gordijnen schuiven langzaam opzij bij aanraking, als een theaterpremière." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "curtain",
  },
  {
    slug: "minimale-couture",
    name: "Minimale Couture",
    tagline: "MEER ZEGGEN DOOR MINDER TE LATEN ZIEN",
    description: "Minimale Couture is de uitnodiging die je niet opvalt — totdat je hem ziet. Veel wit, strakke marges, een typografie die ademt. Geen illustraties, geen patronen, alleen de woorden en de ruimte eromheen. De opening is een vouw die zich ontplooit, als het openen van een brief van handgeschept papier. Voor het stel dat weet dat minder altijd meer is.",
    features: [
      "Vouw-opening: één paneel dat zich langzaam ontvouwt",
      "Minimalistische layout met veel wit",
      "Luxe seriflettertype, uitgebalanceerde typografie",
      "Zwart & wit of champagne variant",
      "17 talen beschikbaar",
      "Aanpasbare lettertypen",
    ],
    img: BASE + "couture-minimale-en-vetrina-93e7c6cd.jpg&w=1200&q=75",
    envelops: [{ label: "Wit", img: BASE + "couture-minimale-en-vetrina-93e7c6cd.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "black", label: "Zwart & Wit" },
      { name: "champagne", label: "Champagne" },
    ],
    music: ["Silence & Grace", "Tender Rose", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de typografie aanpassen?", a: "Ja. Je kiest uit verschillende lettertypen in de editor." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "fold",
  },
  {
    slug: "betoverd-bos",
    name: "Betoverd Bos",
    tagline: "EEN PAD DOOR EEN GESCHILDERD BOS",
    description: "Betoverd Bos is voor wie wil dat de gasten even ergens anders zijn als ze de uitnodiging openen. Een geschilderd bos in groene en roze tinten, met wilde rozen die langs eikenhouten paden klimmen en licht dat door de bladeren valt. De bloemen openen één voor één bij aanraking, als een bos dat wakker wordt. Sprookjesachtig, botanisch, tijdloos.",
    features: [
      "Bloem-opening: bloemen ontvouwen zich één voor één",
      "Geschilderd boslandschap als hero",
      "Wilde rozen en botanisch groen in elke sectie",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "incanto-nel-bosco-en-vetrina-6c056d35.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "incanto-nel-bosco-en-vetrina-6c056d35.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "forest", label: "Diep Groen" },
      { name: "blush", label: "Blush & Groen" },
    ],
    music: ["Enchanted Forest", "Garden Waltz", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleur van de bloemen aanpassen?", a: "Ja. De rozen en botanische details volgen jullie palet." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "floral",
  },
  {
    slug: "riviera-70",
    name: "Riviera 70",
    tagline: "ZONNIG EN VINTAGE, EEN KUST IN DE JAREN ZEVENTIG",
    description: "Riviera 70 is de uitnodiging die smaakt naar zout en zonnebrandcrème. Retro typografie, warm oranje en oud geel, een compositie die doet denken aan de ansichtkaarten die je in de kofferruimte van een citroengele Citroën zou vinden. De opening is een golf die het scherm vult en verdwijnt, als een vlaag zeewind. Voor het stel met karakter en een zwak voor de jaren zeventig.",
    features: [
      "Golf-opening als een vlaag zeewind",
      "Retro typografie en vintage kust-illustraties",
      "Warm oranje en oud geel palet",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "riviera-70-en-vetrina-253c0193.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "riviera-70-en-vetrina-253c0193.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "coral", label: "Koraal & Goud" },
      { name: "turquoise", label: "Turquoise & Zand" },
    ],
    music: ["Côte d'Azur", "Summer Groove", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. Het retro palet is volledig aanpasbaar." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "wave",
  },
  {
    slug: "italiaanse-aquarel",
    name: "Italiaanse Aquarel",
    tagline: "MAJOLICA EN KUST IN ÉÉN AQUAREL",
    description: "Italiaanse Aquarel is de uitnodiging voor wie Amalfi kent — of er altijd van heeft gedroomd. Kleurrijke majolica-tegels, luchtige wassen in citroen en blauw, een fris mediterraan gevoel dat je doet denken aan een terras met uitzicht op de zee. De bloemen openen bij aanraking, als een markt die ontwaakt. Licht, kleurrijk en vol leven.",
    features: [
      "Bloem-opening als een mediterrane markt",
      "Majolica-geïnspireerde details in elke sectie",
      "Aquarel kust-illustraties",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "acquerello-italia-en-vetrina-3869b8cc.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "acquerello-italia-en-vetrina-3869b8cc.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "lemon", label: "Citroen & Blauw" },
      { name: "terracotta", label: "Terracotta & Wit" },
    ],
    music: ["Dolce Vita", "Amalfi Breeze", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De majolica-tinten volgen jullie keuze." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "floral",
  },
  {
    slug: "oro-antico",
    name: "Oro Antico",
    tagline: "BEIGE, OUD GOUD EN BLOEMRIJKE ORNAMENTEN",
    description: "Oro Antico is de uitnodiging van een palazzo dat al eeuwen staat. Beige pleisterwanden, verguld stucwerk, bloemornamentiek in goud die generaties lang is verfijnd. De uitnodiging ontvouwt zich als een brief van zwaar papier — langzaam, met gewicht, zoals alles wat de tijd verdient. Voor het stel dat tijdloze rijkdom wil uitstralen zonder te schreeuwen.",
    features: [
      "Vouw-opening als een brief van zwaar papier",
      "Antiek goud accenten en bloemrijke ornamenten",
      "Warme beige achtergrond",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "oro-antico-en-vetrina-22d36ceb.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "oro-antico-en-vetrina-22d36ceb.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "platinum", label: "Platina & Ivoor" },
      { name: "rose-gold", label: "Rosé Goud" },
    ],
    music: ["Golden Hour", "Amber Glow", "Tender Rose", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. Het antieke goud en de beige tinten zijn aanpasbaar." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "fold",
  },
  {
    slug: "tuscany-chic",
    name: "Tuscany Chic",
    tagline: "TOSCAANS LICHT EN MODERNE VERFIJNING",
    description: "Tuscany Chic is voor het stel dat wil trouwen in een Toscaans landschap — of dat gevoel wil meegeven aan hun gasten, waar de bruiloft ook is. Okerkleurige velden, cypressen in de verte, een openlucht-gevoel dat modern is maar niet koel. De gordijnen van warmte gaan open bij aanraking en onthullen het landschap dat jullie avond omlijst.",
    features: [
      "Gordijn-opening die een Toscaans landschap onthult",
      "Warme oker en terracotta tinten",
      "Modern-rustiek ontwerp",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "tuscany-chic-en-vetrina-3646f639.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "tuscany-chic-en-vetrina-3646f639.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "olive", label: "Olijf & Goud" },
      { name: "terracotta", label: "Terracotta & Cream" },
    ],
    music: ["Dolce Vita", "Harvest Moon", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik een eigen foto gebruiken?", a: "Ja, als achtergrond van de hero." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "curtain",
  },
  {
    slug: "gouden-uur",
    name: "Gouden Uur",
    tagline: "HET LICHT NET VÓÓR ZONSONDERGANG",
    description: "Gouden Uur vangt het moment dat fotografen kennen en bruidsparen nooit vergeten: de laatste twintig minuten voor de zon verdwijnt, als alles goud is en de schaduwen lang. De uitnodiging ontvouwt zich als een briefje geschreven in dat licht — warm, intiem, met haast. Voor het stel dat hun avond wil beginnen met dat gevoel.",
    features: [
      "Vouw-opening in warme gouden tinten",
      "Intieme typografie en romantisch ontwerp",
      "Goud en koper als hoofdpalet",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "tipografico-moderno-en-vetrina-2c921489.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "tipografico-moderno-en-vetrina-2c921489.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "copper", label: "Koper & Goud" },
      { name: "midnight", label: "Middernacht & Goud" },
    ],
    music: ["Golden Hour", "Candlelight", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De gouden en koperen tinten zijn aanpasbaar." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "fold",
  },
  {
    slug: "de-geheime-tuin",
    name: "De Geheime Tuin",
    tagline: "EEN VERBORGEN POORT, EEN ROZENBOOG",
    description: "De Geheime Tuin leidt jullie gasten door een poort die bijna niet te zien is — een smeedijzeren hek begroeid met klimrozen, een pad dat verdwijnt tussen hoge heggen en aan het einde een open plek in de zon. De bloemen openen de weg bij aanraking. De namen van het stel staan gegraveerd als op een zonnige steen, omgeven door alles wat groeit.",
    features: [
      "Bloem-opening als een tuin die ontwaakt",
      "Rozenboog als visuele ingang",
      "Romantisch groen palet met roze accenten",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "giardino-segreto-en-vetrina-c0e0298d.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "giardino-segreto-en-vetrina-c0e0298d.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "rose", label: "Roos & Groen" },
      { name: "white", label: "Wit & Salie" },
    ],
    music: ["Secret Garden", "Garden Waltz", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De rozen en het groen volgen jullie palet." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "floral",
  },
  {
    slug: "tratto-d-inchiostro",
    name: "Tratto d'Inchiostro",
    tagline: "EEN PENSTREEK OP CRÈMEPAPIER",
    description: "Tratto d'Inchiostro is een ode aan de handgeschreven brief. Geen kleur, geen vulling — alleen de lijn en wat die vertelt. Lijnillustraties in één enkele inkt op crèmepapier, als schetsen die iemand in een opwelling heeft gemaakt en nooit heeft weggegooid. De uitnodiging ontvouwt zich als een gevouwen brief, langzaam, met respect voor het papier. Voor het stel dat schrijft in plaats van stuurt.",
    features: [
      "Vouw-opening als een handgeschreven brief",
      "Monochrome lijnillustraties in één inkt",
      "Letterpress-gevoel op crèmepapier",
      "Sepia, marine of grafiet als inktkleur",
      "17 talen beschikbaar",
      "Aanpasbare lettertypen",
    ],
    img: BASE + "tratto-inchiostro-en-vetrina-48f6d0e0.jpg&w=1200&q=75",
    envelops: [{ label: "Crème", img: BASE + "tratto-inchiostro-en-vetrina-48f6d0e0.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "sepia", label: "Sepia" },
      { name: "navy", label: "Marine Inkt" },
    ],
    music: ["Ink & Paper", "Tender Rose", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de inktkleur aanpassen?", a: "Ja. Je kiest uit sepia, marine, grafiet of een eigen kleur." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "fold",
  },
  {
    slug: "idillio",
    name: "Idillio",
    tagline: "EEN GOUDEN STRIK, WITTE ZWANEN, ALLES LICHT",
    description: "Idillio is alles tegelijk: licht, lucht, vreugde en een gouden strik die de dag samenbindt. Twee witte zwanen op een heldere achtergrond, de namen van het stel in een kalligrafisch schrift en een algehele helderheid die geen wolken kent. De strik gaat los bij aanraking — zachter en lichter dan bij Volta Celeste, want Idillio danst waar de ander zweeft.",
    features: [
      "Strik-opening: gouden strik gaat los bij aanraking",
      "Witte zwanen en lichte aquarelwassen",
      "Helder en vrolijk palet",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "idillio-en-vetrina-4806113a.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "idillio-en-vetrina-4806113a.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "gold", label: "Goud & Wit" },
      { name: "blush", label: "Blush & Goud" },
    ],
    music: ["Golden Hour", "Swan Lake", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Wat is het verschil met Het Zwanenmeer?", a: "Idillio is lichter en vrolijker. Het Zwanenmeer is meditatief. Beide hebben zwanen, maar het gevoel is anders." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "bow",
  },
  {
    slug: "romantisch-botanisch",
    name: "Romantisch Botanisch",
    tagline: "BOTANISCHE PAGINA'S UIT EEN OUD PLANTENBOEK",
    description: "Romantisch Botanisch ziet eruit als een pagina die iemand heeft losgenomen uit een 18e-eeuws herbariumboek — varens, bloesem en wilde bloemen in zachte groene en roze tinten, gedrukt op crèmepapier. De bloemen ontvouwen zich bij aanraking als een herbarium dat wordt opengeslagen. Naturalistisch, romantisch en tijdloos mooi.",
    features: [
      "Herbarium-opening: botanische illustraties ontvouwen zich",
      "Varens, bloesem en wilde bloemen in elke sectie",
      "Delicate groene en roze tinten",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "botanico-romantico-en-vetrina-5a476f93.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "botanico-romantico-en-vetrina-5a476f93.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "forest", label: "Diep Groen" },
      { name: "blush", label: "Blush Botanisch" },
    ],
    music: ["Botanical Dreams", "Garden Waltz", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. De botanische tinten volgen jullie palet." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "floral",
  },
  {
    slug: "strawberry-matcha",
    name: "Strawberry Matcha",
    tagline: "FRIS, SPEELS EN ONVERWACHT MOOI",
    description: "Strawberry Matcha is de uitnodiging voor het stel dat niet wil kiezen tussen klassiek en eigentijds — en uiteindelijk iets bedenkt dat geen van beide is. Matcha-groen en aardbeirood, een combinatie die op papier niet zou moeten werken en in de uitnodiging precies goed is. De opening is een golf die het scherm vult als een kopje thee dat wordt ingeschonken. Fris, energiek en onmiskenbaar.",
    features: [
      "Golf-opening als een kopje thee",
      "Matcha-groen en aardbeirood als hoofdpalet",
      "Modern en fris ontwerp",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "strawberry-matcha-en-vetrina-4c490953.jpg&w=1200&q=75",
    envelops: [{ label: "Ivoor", img: BASE + "strawberry-matcha-en-vetrina-4c490953.jpg&w=400&q=75" }],
    colors: [
      { name: "origineel", label: "Origineel" },
      { name: "matcha", label: "Matcha & Cream" },
      { name: "strawberry", label: "Aardbei & Wit" },
    ],
    music: ["Fresh Morning", "Garden Waltz", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Kan ik de kleuren aanpassen?", a: "Ja. Alle tinten zijn volledig aanpasbaar." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd. Elke gast bevestigt met één tik." },
    ],
    price: "89",
    openingStyle: "wave",
  },
  {
    slug: "toile-de-jouy",
    name: "Toile de Jouy",
    tagline: "KLASSIEKE TOILE IN VIER TINTEN",
    description: "Toile de Jouy is Frans, klassiek en net iets te mooi om weg te gooien. Een toile-print met landelijke taferelen — herders, bomen, fonteinen — in blauw, rood, groen of zwart op crème papier. De uitnodiging ontvouwt zich als een brief die iemand in de 18e eeuw zou hebben gestuurd: een paneel dat langzaam opengaat en het tafereel onthult. Een zilveren of wit lint sluit de envelop. Voor het stel dat weet wat Versailles is.",
    features: [
      "Vouw-opening als een 18e-eeuwse brief",
      "Klassieke toile-print in vier kleurvarianten",
      "Zilveren of wit lint op de envelop",
      "Frans-klassiek ontwerp",
      "17 talen beschikbaar",
      "Aanpasbare kleuren en lettertypen",
    ],
    img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=1200&q=75",
    envelops: [
      { label: "Toile Blauw", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Rood", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Groen", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
      { label: "Toile Zwart", img: BASE + "toile-bleu-en-vetrina-a0fc5d6a.jpg&w=400&q=75" },
    ],
    colors: [
      { name: "blauw", label: "Toile Blauw" },
      { name: "rood", label: "Toile Rood" },
      { name: "groen", label: "Toile Groen" },
      { name: "zwart", label: "Toile Zwart" },
    ],
    music: ["Versailles", "Tender Rose", "Amber Glow", "Geen muziek"],
    faq: [
      { q: "Hoeveel kleurvarianten zijn er?", a: "Vier: blauw, rood, groen en zwart. Alle vier op crème papier." },
      { q: "Hoe werkt de RSVP?", a: "Ingebouwd en zonder app." },
    ],
    price: "89",
    openingStyle: "fold",
  },
];

export function getTemplate(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}
